language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ea018b0605ca_key -iv $encrypted_ea018b0605ca_iv
    -in travis.enc -out ~/.ssh/travis -d
  - chmod 600 ~/.ssh/travis
  - echo -e "Host 60.205.188.39\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install hexo-cli -g
install:
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name  "liebes"
  - git config user.email "wanghaichi0403@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - ls -al ~/.ssh
  - whoami
  - rsync -az -vv --delete -e 'ssh -i ~/.ssh/travis' public/ root@www.liebes.top:/var/www/blog
addons:
  ssh_known_hosts: www.liebes.top:22
branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/wanghaichi/wanghaichi.github.io.git
