language: node_js # 声明环境为node

node_js: stable

# Travis-CI Caching
cache:
  apt: true
  directories:
    - node_modules # 缓存node_modules文件夹

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
# S: Build Lifecycle
install:
  - npm install # 下载依赖

script:
  - hexo clean
  - hexo g 


after_script: # 推送到github的部分
  - ./publish-to-gh-pages.sh

addons:
  ssh_known_hosts: liebes.top:22

branches:
  only:
    - hexo # 只对hexo分支构建

env: # 环境变量
 global:
   - GH_REF: github.com/wanghaichi/wanghaichi.github.io.git # 我的仓库地址
